name = "JumpSim"
default_targets = ["win32", "win64", "lovejs", "macos"] # "appimage" must be run from WSL2 for a linux build
build_directory = "../builds"

love_files = [
    "**/*",           # Include everything
    "-*/.*",          # Exclude hidden files
    "-**/*.git*",     # Exclude git files
]
