name = "JumpSim"
default_targets = ["win32", "win64"]
build_directory = "../builds"

love_files = [
    "**/*",           # Include everything
    "-*/.*",          # Exclude hidden files
    "-**/*.git*",     # Exclude git files
]
